// Public-domain poems for quick trial. Chinese classical texts are as commonly
// printed; translations are not included (only originals). Energy tags help
// pick something that matches the moment.
window.POET_POEMS = [
  {title: "静夜思", author: "李白", era: "唐", lang: "zh", tag: "月夜·思乡", text: "床前明月光，\n疑是地上霜。\n举头望明月，\n低头思故乡。"},
  {title: "春晓", author: "孟浩然", era: "唐", lang: "zh", tag: "清晨·柔软", text: "春眠不觉晓，\n处处闻啼鸟。\n夜来风雨声，\n花落知多少。"},
  {title: "登鹳雀楼", author: "王之涣", era: "唐", lang: "zh", tag: "登高·向上", text: "白日依山尽，\n黄河入海流。\n欲穷千里目，\n更上一层楼。"},
  {title: "相思", author: "王维", era: "唐", lang: "zh", tag: "思念·温柔", text: "红豆生南国，\n春来发几枝。\n愿君多采撷，\n此物最相思。"},
  {title: "江雪", author: "柳宗元", era: "唐", lang: "zh", tag: "孤寂·冷", text: "千山鸟飞绝，\n万径人踪灭。\n孤舟蓑笠翁，\n独钓寒江雪。"},
  {title: "春夜喜雨（前四句）", author: "杜甫", era: "唐", lang: "zh", tag: "细雨·安静", text: "好雨知时节，\n当春乃发生。\n随风潜入夜，\n润物细无声。"},
  {title: "出塞", author: "王昌龄", era: "唐", lang: "zh", tag: "边塞·豪迈", text: "秦时明月汉时关，\n万里长征人未还。\n但使龙城飞将在，\n不教胡马度阴山。"},
  {title: "早发白帝城", author: "李白", era: "唐", lang: "zh", tag: "轻快·奔流", text: "朝辞白帝彩云间，\n千里江陵一日还。\n两岸猿声啼不住，\n轻舟已过万重山。"},
  {title: "将进酒（节选）", author: "李白", era: "唐", lang: "zh", tag: "狂放·能量", text: "君不见黄河之水天上来，奔流到海不复回。\n君不见高堂明镜悲白发，朝如青丝暮成雪。\n\n人生得意须尽欢，莫使金樽空对月。\n天生我材必有用，千金散尽还复来。"},
  {title: "敕勒歌", author: "北朝民歌", era: "南北朝", lang: "zh", tag: "辽阔·风", text: "敕勒川，阴山下。\n天似穹庐，笼盖四野。\n\n天苍苍，野茫茫，\n风吹草低见牛羊。"},
  {title: "水调歌头（节选）", author: "苏轼", era: "宋", lang: "zh", tag: "明月·问天", text: "明月几时有？把酒问青天。\n不知天上宫阙，今夕是何年。\n\n人有悲欢离合，月有阴晴圆缺，此事古难全。\n但愿人长久，千里共婵娟。"},
  {title: "念奴娇·赤壁怀古（节选）", author: "苏轼", era: "宋", lang: "zh", tag: "大江·豪杰", text: "大江东去，浪淘尽，千古风流人物。\n\n乱石穿空，惊涛拍岸，卷起千堆雪。\n江山如画，一时多少豪杰。"},
  {title: "定风波（节选）", author: "苏轼", era: "宋", lang: "zh", tag: "从容·释然", text: "莫听穿林打叶声，何妨吟啸且徐行。\n竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。\n\n回首向来萧瑟处，归去，也无风雨也无晴。"},
  {title: "声声慢（节选）", author: "李清照", era: "宋", lang: "zh", tag: "凄清·低回", text: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。\n乍暖还寒时候，最难将息。"},
  {title: "天净沙·秋思", author: "马致远", era: "元", lang: "zh", tag: "黄昏·天涯", text: "枯藤老树昏鸦，\n小桥流水人家，\n古道西风瘦马。\n夕阳西下，\n断肠人在天涯。"},
  {title: "再别康桥（节选）", author: "徐志摩", era: "现代", lang: "zh", tag: "轻盈·告别", text: "轻轻的我走了，正如我轻轻的来；\n我轻轻的招手，作别西天的云彩。\n\n那河畔的金柳，是夕阳中的新娘；\n波光里的艳影，在我的心头荡漾。"},
  {title: "雨巷（节选）", author: "戴望舒", era: "现代", lang: "zh", tag: "雨·彷徨", text: "撑着油纸伞，独自\n彷徨在悠长、悠长\n又寂寥的雨巷，\n我希望逢着\n一个丁香一样地\n结着愁怨的姑娘。"},
  {title: "Sonnet 18 (excerpt)", author: "William Shakespeare", era: "1609", lang: "en", tag: "summer · love", text: "Shall I compare thee to a summer's day?\nThou art more lovely and more temperate.\nRough winds do shake the darling buds of May,\nAnd summer's lease hath all too short a date.\n\nSo long as men can breathe or eyes can see,\nSo long lives this, and this gives life to thee."},
  {title: "Hope is the thing with feathers", author: "Emily Dickinson", era: "1861", lang: "en", tag: "hope · light", text: "Hope is the thing with feathers\nThat perches in the soul,\nAnd sings the tune without the words,\nAnd never stops at all."},
  {title: "The Road Not Taken (last stanza)", author: "Robert Frost", era: "1916", lang: "en", tag: "choice · reflective", text: "I shall be telling this with a sigh\nSomewhere ages and ages hence:\nTwo roads diverged in a wood, and I,\nI took the one less traveled by,\nAnd that has made all the difference."},
  {title: "The Tyger (first stanza)", author: "William Blake", era: "1794", lang: "en", tag: "fire · power", text: "Tyger Tyger, burning bright,\nIn the forests of the night;\nWhat immortal hand or eye,\nCould frame thy fearful symmetry?"},
  {title: "I Wandered Lonely as a Cloud (first stanza)", author: "William Wordsworth", era: "1807", lang: "en", tag: "flowers · calm", text: "I wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils;\nBeside the lake, beneath the trees,\nFluttering and dancing in the breeze."},
  {title: "Invictus (last stanza)", author: "William Ernest Henley", era: "1888", lang: "en", tag: "courage · energy", text: "It matters not how strait the gate,\nHow charged with punishments the scroll,\nI am the master of my fate,\nI am the captain of my soul."},
  {title: "O Captain! My Captain! (opening)", author: "Walt Whitman", era: "1865", lang: "en", tag: "triumph · grief", text: "O Captain! my Captain! our fearful trip is done,\nThe ship has weather'd every rack, the prize we sought is won,\nThe port is near, the bells I hear, the people all exulting,\nWhile follow eyes the steady keel, the vessel grim and daring."},
  {title: "When You Are Old (first stanza)", author: "W. B. Yeats", era: "1893", lang: "en", tag: "memory · tender", text: "When you are old and grey and full of sleep,\nAnd nodding by the fire, take down this book,\nAnd slowly read, and dream of the soft look\nYour eyes had once, and of their shadows deep."},
  {title: "Ulysses (closing lines)", author: "Alfred Tennyson", era: "1842", lang: "en", tag: "resolve · drive", text: "Though much is taken, much abides; and though\nWe are not now that strength which in old days\nMoved earth and heaven, that which we are, we are;\nOne equal temper of heroic hearts,\nMade weak by time and fate, but strong in will\nTo strive, to seek, to find, and not to yield."},
  {title: "Ozymandias (excerpt)", author: "Percy Bysshe Shelley", era: "1818", lang: "en", tag: "ruins · time", text: "And on the pedestal, these words appear:\nMy name is Ozymandias, King of Kings;\nLook on my Works, ye Mighty, and despair!\nNothing beside remains. Round the decay\nOf that colossal Wreck, boundless and bare\nThe lone and level sands stretch far away."},
  {title: "Wandrers Nachtlied II", author: "Johann Wolfgang von Goethe", era: "1780", lang: "de", tag: "still · night", text: "Über allen Gipfeln\nIst Ruh,\nIn allen Wipfeln\nSpürest du\nKaum einen Hauch;\nDie Vögelein schweigen im Walde.\nWarte nur, balde\nRuhest du auch."},
  {title: "Herbsttag (opening)", author: "Rainer Maria Rilke", era: "1902", lang: "de", tag: "autumn · ripe", text: "Herr: es ist Zeit. Der Sommer war sehr groß.\nLeg deinen Schatten auf die Sonnenuhren,\nund auf den Fluren laß die Winde los."},
];
